title: LPFP Le Petit Fab-Lab de Paris
description: Ateliers aux Petit Fab-Lab de Paris.
author: Asso [Fab-Lab]
logo: LPFP_square_logo.png
github: https://github.com/LPFP
about: Le petit Fab-Lab de Paris
mail: ateliers@lepetitfablabdeparis.fr

#asso
nom: "Le Petit Fablab De Paris"
nom-short: LPFP
adr: 86 Avenue Philippe Auguste 75011 Paris
email: bonjour [at] lepetitfablabdeparis [point] fr
tel: +33 9 51 58 75 50
calendrier: "https://www.google.com/calendar/embed?height=600&amp;wkst=5&amp;bgcolor=%23FFFFFF&amp;src=dk065gt1qtr9maf1p16o1kib5o%40group.calendar.google.com&amp;color=%231B887A&amp"
atelier: Samedi de 12h00 à 14h00
pop: Samedi et Dimanche de 14h00 à 16h00
president: "Laurent Barnier"
vicepresident: null
tresorier: "Sakada Ly"
porteparole: null
secretaire: null
tarif: "de 120€/an à 80€/an"

token:
  mapbox: pk.eyJ1Ijoicm9ieXJlbXp5IiwiYSI6ImNpc2RtemNqazAwMTkyeG82MHBlemx6aTMifQ.wSeiG1ERx30Dwc27idsDfQ
  mapillary: enpzOU5oNGZIQW1NLTI0T2JrdGFmQTo0NDJjMTkzMzEwMDQxNGE4
  pgp:

baseurl: /
url: "https://LPFP.github.io"

disqus_shortname: atelierslpfp

staticman:
  allowedFields  : ['name', 'email', 'message']
  branch         : "master"
  commitMessage  : "New comment."
  filename       : comment-{@timestamp}
  generatedFields:
    date:
      type       : "date"
      options:
        format   : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
  format         : "yml"
  moderation     : false
  path           : "_data/comments/{options.slug}"
  requiredFields : ['name', 'message']
  transforms:
    email        : "md5"

# authors
lpfp:
  twitter: lpfablabparis
  github: LPFP
  facebook: lepetitfablabdeparis
  lpfp: "Le Petit FabLab de Paris"
  quote: "Admin aka The Bot auto Reply & spam test"

remi:
  twitter: remstw
  github: robyremzy
  pgp: "2C4B AEF1 B2E7 D676"
  lpfp: "Fab Manager du Dimanche"
  quote: "Open Data, Carto-Hacker, Dj'vlopper sur outils libres"

# nom:  #idem "poster" idem static/img/nom.jpg /!\ photo en .jpg
#   twitter:
#   github:
#   facebook:
#   pgp: "" #public key 64bit
#   lpfp: "" #role au petit fablab
#   quote: ""

share:
  twitter_username: lpfablabparis
  fb_appid: LePetitFablabDeParis
  mailchimp:

gist:
  noscript: false

enableTags: true
tagarray: []

paginate: 12
per_page: 4
paginate_path: "/page:num/"
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: true

gems: ['jekyll-paginate', 'jemoji', 'jekyll-gist']
